### PR TITLE
Optimize provision script.

### PR DESCRIPTION
**Pull request by jmrodri**
The original provision script took:
real    1m26.463s
user    0m30.512s
sys 0m3.306s

By refactoring it a bit to avoid multiple yum calls, and dumping the disable
stuff to /dev/null we can save 20 seconds on each run.

real    1m6.916s
user    0m22.776s
sys 0m2.662s

### CODE REVIEW

**Comment by jmrodri** [comment]
Want to add a new repo? just add it to the repos variable at the top. Want to add a new RPM? add it to the pkgs variable. We will invoke yum only ones with all the packages. And subscription-manager only twice (once for disable, and once for enabling the rest of the repos)

**Comment by jmrodri** [comment]
vagrant up before optimization:

```
real    3m52.178s
user    0m6.552s
sys 0m1.257s
```

After optimization, this PR lowers it by 30 seconds:

```
real    3m20.262s
user    0m6.013s
sys 0m1.184s
```

**Comment by eriknelson** [comment]
This looks good to me, will defer to @jwmatthews for ACK

**Comment by jmrodri** [comment]
It's been ready for a while. ;)

**Comment by eriknelson** [comment]
Merging!

**Pull request merged**
